steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '--build-arg', 'BACKEND_URL=${_BACKEND_URL}',
    '-t', 'gcr.io/$PROJECT_ID/equilabel-frontend',
    '.'
  ]
images:
- 'gcr.io/$PROJECT_ID/equilabel-frontend'
options:
  machineType: 'E2_HIGHCPU_8'
